# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 William Johnason / axoviq.com
from __future__ import annotations

import os
from pathlib import Path
from typing import Optional

import typer

from synthadoc.cli._wiki import read_registry_all, CROSS_WIKI_ROUTING_PATH  # shared constant
from synthadoc.cli.query import print_cross_wiki_result  # shared output helper
from synthadoc.cli.status import render_status_all       # shared table helper

cross_wiki_app = typer.Typer(name="cross-wiki", help="Cross-wiki federation commands.")
routing_app = typer.Typer(name="routing", help="Manage CROSS_WIKI_ROUTING.md.")
cross_wiki_app.add_typer(routing_app)

# Use the imported CROSS_WIKI_ROUTING_PATH constant — do NOT redefine _ROUTING_PATH locally.


@cross_wiki_app.command("query")
def cross_wiki_query_cmd(
    question: str = typer.Argument(...),
    timeout: int = typer.Option(90, "--timeout"),
):
    """Fan-out query across all relevant registered wikis. Alias for `synthadoc query --cross-wiki`."""
    from synthadoc.cli._wiki import resolve_wiki
    from synthadoc.cli._http import post
    wiki = resolve_wiki(None)
    result = post(wiki, "/cross-wiki/query", {"question": question}, timeout=timeout, llm=True)
    print_cross_wiki_result(result, wiki)  # shared helper — do NOT duplicate output logic here


@cross_wiki_app.command("status")
def cross_wiki_status_cmd():
    """Show status for all registered wikis. Alias for `synthadoc status --all`."""
    render_status_all(read_registry_all())  # shared helper — do NOT reimplement the table


# NO _status_all() function here — that logic lives in status.py as render_status_all().


@routing_app.command("init")
def routing_init():
    """Scaffold CROSS_WIKI_ROUTING.md from the current registry."""
    registry = read_registry_all()
    # Use the imported constant — do NOT re-define the path locally
    if CROSS_WIKI_ROUTING_PATH.exists():
        typer.confirm(f"{CROSS_WIKI_ROUTING_PATH} already exists — overwrite?", abort=True)
    lines = ["# Cross-Wiki Routing\n", "# Generated by `synthadoc cross-wiki routing init`\n\n"]
    wiki_names = list(registry.keys())
    lines.append("## default\n")
    lines.append(f"wikis: {', '.join(wiki_names)}\n")
    lines.append("keywords:\n")
    CROSS_WIKI_ROUTING_PATH.write_text("".join(lines), encoding="utf-8")
    typer.echo(f"Created {CROSS_WIKI_ROUTING_PATH}")
    typer.echo("Edit it to add keyword-based routing rules per section.")


@routing_app.command("show")
def routing_show():
    """Print the current CROSS_WIKI_ROUTING.md."""
    if not CROSS_WIKI_ROUTING_PATH.exists():
        typer.echo(f"No routing file found at {CROSS_WIKI_ROUTING_PATH}.")
        typer.echo("Run `synthadoc cross-wiki routing init` to create one.")
        return
    typer.echo(CROSS_WIKI_ROUTING_PATH.read_text(encoding="utf-8"))


@routing_app.command("edit")
def routing_edit():
    """Open CROSS_WIKI_ROUTING.md in $EDITOR."""
    if not CROSS_WIKI_ROUTING_PATH.exists():
        typer.echo("No routing file. Run `synthadoc cross-wiki routing init` first.")
        raise typer.Exit(1)
    editor = os.environ.get("EDITOR", "notepad" if os.name == "nt" else "nano")
    os.execlp(editor, editor, str(CROSS_WIKI_ROUTING_PATH))
