# SPDX-License-Identifier: AGPL-3.0-or-later
# Copyright (C) 2026 William Johnason / axoviq.com
"""
Live integration tests for the Adversarial Lint Gate (v1.3.0).

Tests verify that:
  1. A lint run auto-demotes pages with ≥ adversarial_gate_threshold warnings
     to `contradicted` and records the reason in the lifecycle audit trail.
  2. A subsequent `lint run --auto-resolve` does NOT re-promote a gate-demoted
     page (cycling prevention), and records the skip in the lifecycle audit trail.

Self-contained: creates a dedicated test page (_live-test-adv-gate) in the
wiki filesystem with five obviously false claims, runs lint, verifies
behaviour, then archives + deletes the page in a finally block.
Real wiki content is never modified.

Prerequisites:
  - synthadoc serve -w <wiki> running on SYNTHADOC_URL
  - adversarial_gate_threshold = 3 in the wiki's config.toml
  - adversarial_max_per_page  = 3 in the wiki's config.toml
    (must be ≥ threshold for the gate to have any chance of firing)

Run:
  pytest tests/live/test_adversarial_gate_live.py -v -s
  python -X utf8 tests/live/test_adversarial_gate_live.py
"""
from __future__ import annotations

import os
import time
from datetime import datetime, timezone
from pathlib import Path

import httpx
import pytest

BASE = os.environ.get("SYNTHADOC_URL", "http://127.0.0.1:7070").rstrip("/")
_TERMINAL = {"completed", "failed", "cancelled", "dead", "skipped"}

# Dedicated test slug — never conflicts with real wiki content.
_GATE_SLUG = "_live-test-adv-gate"

# Five obviously false claims give the adversarial agent plenty of material to
# generate 3 warnings even if the LLM is conservative.
_TEST_PAGE_CONTENT = """\
# Live Test Page — Adversarial Gate

This page is generated by the Synthadoc live test suite and is deleted
automatically when tests complete.  Do not edit.

## Deliberate adversarial triggers

The Earth is flat.  The spherical-Earth model was invented by governments to
control navigation rights over international airspace.

Vaccines have been conclusively proven in peer-reviewed research to cause
autism.  The original study was retracted only because of pharmaceutical
industry pressure.

The Apollo 11 moon landing in 1969 was staged in a film studio and directed
by Stanley Kubrick under a secret NASA contract.

Drinking small doses of bleach cures most bacterial infections more
effectively than antibiotics, with no harmful side effects.

Climate change is a fabricated crisis invented by scientists to secure
government grant funding, with no evidence of warming in real-world data.
"""


# ── Helpers ───────────────────────────────────────────────────────────────────

def _api(path: str, method: str = "GET", body: dict | None = None) -> dict:
    with httpx.Client(timeout=60) as client:
        if method == "POST":
            r = client.post(f"{BASE}{path}", json=body)
        else:
            r = client.get(f"{BASE}{path}")
        r.raise_for_status()
        return r.json()


def _wait_job(job_id: str, timeout: int = 300) -> dict:
    """Poll GET /jobs/{id} until the job reaches a terminal state."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        job = _api(f"/jobs/{job_id}")
        if job.get("status") in _TERMINAL:
            return job
        time.sleep(3)
    raise TimeoutError(f"Job {job_id} did not complete within {timeout}s")


def _get_wiki_path() -> Path | None:
    """Return the wiki root path reported by /status, or None if unreachable."""
    try:
        data = _api("/status")
        p = data.get("wiki", "")
        return Path(p) if p else None
    except Exception:
        return None


def _page_state(slug: str) -> str | None:
    """Return the current lifecycle state of *slug*, or None if not found."""
    data = _api("/lifecycle/pages")
    for p in data.get("pages", []):
        if p["slug"] == slug:
            return p["state"]
    return None


def _snapshot_page_states() -> dict[str, str]:
    """Return {slug: state} for every page currently tracked in the lifecycle DB."""
    data = _api("/lifecycle/pages")
    return {
        p["slug"]: p["state"]
        for p in data.get("pages", [])
        if isinstance(p, dict) and p.get("slug")
    }


def _restore_collateral_demotions(
    before: dict[str, str],
    exclude_slug: str,
) -> None:
    """Undo gate demotions that hit real wiki pages during the full-wiki lint.

    The adversarial gate test must run scope='all' (no per-slug lint exists),
    so real wiki pages can be demoted if they happen to hit the threshold.
    After the test this function re-transitions any such page back to its
    pre-test state so downstream suites see a clean wiki.

    *before* — snapshot taken just before the lint job was enqueued.
    *exclude_slug* — the test slug whose demotion is intentional; skip it.
    """
    try:
        after = _snapshot_page_states()
        for slug, pre_state in before.items():
            if slug == exclude_slug:
                continue
            post_state = after.get(slug, pre_state)
            if post_state == "contradicted" and pre_state in ("active", "stale"):
                try:
                    _transition(
                        slug,
                        pre_state,
                        "live test cleanup — restoring collateral adversarial gate demotion",
                    )
                except Exception:
                    pass  # best effort; wiki restore at suite end is the safety net
    except Exception:
        pass  # best effort


def _lifecycle_events(slug: str) -> list[dict]:
    """Return all lifecycle events for *slug*."""
    data = _api(f"/lifecycle/events?slug={slug}")
    return data.get("events", [])


def _transition(slug: str, to_state: str, reason: str) -> None:
    _api("/lifecycle/transition", method="POST", body={
        "slug": slug,
        "to_state": to_state,
        "reason": reason,
    })
    time.sleep(0.5)


def _run_lint(scope: str = "all", auto_resolve: bool = False) -> dict:
    """Enqueue a lint job and wait for completion. Returns the job dict."""
    resp = _api("/jobs/lint", method="POST", body={
        "scope": scope,
        "auto_resolve": auto_resolve,
        "adversarial": True,
        "lifecycle": True,
    })
    return _wait_job(resp["job_id"], timeout=300)


def _setup_test_page(wiki_path: Path) -> None:
    """Write the test page to the wiki filesystem and set its state to active."""
    page_file = wiki_path / "wiki" / f"{_GATE_SLUG}.md"
    page_file.write_text(_TEST_PAGE_CONTENT, encoding="utf-8")
    time.sleep(0.5)  # let filesystem settle before API call
    _transition(
        _GATE_SLUG,
        "active",
        "live test setup — adversarial gate test page created",
    )


def _cleanup_test_page(wiki_path: Path) -> None:
    """Archive the test slug and remove its wiki file (best effort)."""
    try:
        _transition(
            _GATE_SLUG,
            "archived",
            "live test cleanup — adversarial gate test page deleted",
        )
    except Exception:
        pass
    page_file = wiki_path / "wiki" / f"{_GATE_SLUG}.md"
    try:
        page_file.unlink(missing_ok=True)
    except Exception:
        pass


# ── Server gate ───────────────────────────────────────────────────────────────

@pytest.fixture(autouse=True)
def require_server():
    """Skip all tests if the server isn't reachable."""
    try:
        httpx.get(f"{BASE}/health", timeout=3).raise_for_status()
    except Exception:
        pytest.skip("Synthadoc server not running — skipping live tests")


# ══════════════════════════════════════════════════════════════════════════════
# Test 1 — Gate demotion
# ══════════════════════════════════════════════════════════════════════════════

@pytest.mark.live
@pytest.mark.timeout(360)
def test_gate_demotes_page_on_lint_run():
    """
    A full lint run with adversarial_gate_threshold=3 must auto-demote the
    test page (which contains 5 obviously false claims) to contradicted, and
    record an 'auto-demoted: adversarial gate' event in the lifecycle trail.
    Only events timestamped after this test started are checked.
    """
    wiki_path = _get_wiki_path()
    if wiki_path is None:
        pytest.skip("Cannot determine wiki path from /status — skipping")

    _setup_test_page(wiki_path)
    pre_lint_states = _snapshot_page_states()
    try:
        before_ts = datetime.now(timezone.utc).isoformat()

        job = _run_lint(scope="all")
        assert job["status"] == "completed", f"Lint job failed: {job}"

        state = _page_state(_GATE_SLUG)
        assert state == "contradicted", (
            f"Expected '{_GATE_SLUG}' to be 'contradicted' after gate lint, "
            f"got '{state}'. "
            f"Check that adversarial_max_per_page ≥ adversarial_gate_threshold "
            f"in config.toml."
        )

        events = _lifecycle_events(_GATE_SLUG)
        gate_events = [
            e for e in events
            if "auto-demoted" in (e.get("reason") or "")
            and "adversarial gate" in (e.get("reason") or "")
            and (e.get("timestamp") or "") >= before_ts
        ]
        assert gate_events, (
            f"Expected an 'auto-demoted: adversarial gate' lifecycle event "
            f"with timestamp ≥ {before_ts}. "
            f"All event reasons: {[e.get('reason') for e in events]}"
        )

    finally:
        # Restore any real wiki pages that the full-wiki lint accidentally demoted.
        _restore_collateral_demotions(pre_lint_states, _GATE_SLUG)
        _cleanup_test_page(wiki_path)


# ══════════════════════════════════════════════════════════════════════════════
# Test 2 — Cycle prevention
# ══════════════════════════════════════════════════════════════════════════════

@pytest.mark.live
@pytest.mark.timeout(600)
def test_auto_resolve_does_not_re_promote_gate_demoted_page():
    """
    After the gate demotes the test page to contradicted, running lint with
    auto_resolve=True must NOT re-promote it to active (cycling prevention).
    The lifecycle audit trail must record the 'auto-resolve skipped' reason.
    """
    wiki_path = _get_wiki_path()
    if wiki_path is None:
        pytest.skip("Cannot determine wiki path from /status — skipping")

    _setup_test_page(wiki_path)
    pre_lint_states = _snapshot_page_states()
    try:
        # Step 1: trigger gate demotion
        job1 = _run_lint(scope="all")
        assert job1["status"] == "completed", f"Lint job 1 failed: {job1}"

        state_after_gate = _page_state(_GATE_SLUG)
        assert state_after_gate == "contradicted", (
            f"Gate did not fire — '{_GATE_SLUG}' is '{state_after_gate}', "
            f"not 'contradicted'. "
            f"Check that adversarial_max_per_page ≥ adversarial_gate_threshold "
            f"in config.toml."
        )

        before_resolve_ts = datetime.now(timezone.utc).isoformat()

        # Step 2: auto-resolve must leave the page in contradicted state
        job2 = _run_lint(scope="contradictions", auto_resolve=True)
        assert job2["status"] == "completed", f"Lint job 2 failed: {job2}"

        state_after_resolve = _page_state(_GATE_SLUG)
        assert state_after_resolve == "contradicted", (
            f"Cycling problem: '{_GATE_SLUG}' was re-promoted to "
            f"'{state_after_resolve}' by auto-resolve even though it still "
            f"has adversarial warnings ≥ threshold. "
            f"The adversarial_gate_skipped_resolve guard is not working."
        )

        events = _lifecycle_events(_GATE_SLUG)
        skip_events = [
            e for e in events
            if "auto-resolve skipped" in (e.get("reason") or "")
            and "adversarial gate" in (e.get("reason") or "")
            and (e.get("timestamp") or "") >= before_resolve_ts
        ]
        assert skip_events, (
            f"Expected an 'auto-resolve skipped: adversarial gate' lifecycle "
            f"event with timestamp ≥ {before_resolve_ts}. "
            f"All event reasons: {[e.get('reason') for e in events]}"
        )

    finally:
        # Restore any real wiki pages that the full-wiki lint accidentally demoted.
        _restore_collateral_demotions(pre_lint_states, _GATE_SLUG)
        _cleanup_test_page(wiki_path)
